# # This file has been auto-generated by i3-config-wizard(1).
# # It will not be overwritten, so edit it as you like.
# #
# # Should you change your keyboard layout some time, delete
# # this file and re-run i3-config-wizard(1).
# #

# # i3 config file (v4)
# #
# # Please see http://i3wm.org/docs/userguide.html for a complete reference!

# set $mod Mod4

# # Font for window titles. Will also be used by the bar unless a different font
# # is used in the bar {} block below.
# #font pango:monospace 8

# # This font is widely installed, provides lots of unicode glyphs, right-to-left
# # text rendering and scalability on retina/hidpi displays (thanks to pango).
# font pango:DejaVu Sans Mono 8

# # Before i3 v4.8, we used to recommend this one as the default:
# # font -misc-fixed-medium-r-normal--13-120-75-75-C-70-iso10646-1
# # The font above is very space-efficient, that is, it looks good, sharp and
# # clear in small sizes. However, its unicode glyph coverage is limited, the old
# # X core fonts rendering does not support right-to-left and this being a bitmap
# # font, it doesn’t scale on retina/hidpi displays.

# # Use Mouse+$mod to drag floating windows to their wanted position
# floating_modifier $mod

# # start a terminal
# bindsym $mod+Return exec i3-sensible-terminal

# # kill focused window
# bindsym $mod+Shift+b kill

# # start dmenu (a program launcher)
# bindsym $mod+i exec dmenu_run
# # There also is the (new) i3-dmenu-desktop which only displays applications
# # shipping a .desktop file. It is a wrapper around dmenu, so you need that
# # installed.
# # bindsym $mod+d exec --no-startup-id i3-dmenu-desktop

# # change focus
# bindsym $mod+t focus left
# bindsym $mod+s focus down
# bindsym $mod+r focus up
# bindsym $mod+n focus right

# # alternatively, you can use the cursor keys:
# bindsym $mod+Left focus left
# bindsym $mod+Down focus down
# bindsym $mod+Up focus up
# bindsym $mod+Right focus right

# # move focused window
# bindsym $mod+Shift+t move left
# bindsym $mod+Shift+s move down
# bindsym $mod+Shift+r move up
# bindsym $mod+Shift+n move right

# # alternatively, you can use the cursor keys:
# bindsym $mod+Shift+Left move left
# bindsym $mod+Shift+Down move down
# bindsym $mod+Shift+Up move up
# bindsym $mod+Shift+Right move right

# # split in horizontal orientation
# bindsym $mod+c split h

# # split in vertical orientation
# bindsym $mod+period split v

# # enter fullscreen mode for the focused container
# bindsym $mod+e fullscreen toggle

# # change container layout (stacked, tabbed, toggle split)
# bindsym $mod+u layout stacking
# bindsym $mod+eacute layout tabbed
# bindsym $mod+p layout toggle split

# # toggle tiling / floating
# bindsym $mod+Shift+space floating toggle

# # change focus between tiling / floating windows
# bindsym $mod+space focus mode_toggle

# # focus the parent container
# bindsym $mod+a focus parent

# # focus the child container
# #bindsym $mod+d focus child

# # switch to workspace
# bindsym $mod+quotedbl workspace 1
# bindsym $mod+guillemotleft workspace 2
# bindsym $mod+guillemotright workspace 3
# bindsym $mod+parenleft workspace 4
# bindsym $mod+parenright workspace 5
# bindsym $mod+at workspace 6
# bindsym $mod+plus workspace 7
# bindsym $mod+minus workspace 8
# bindsym $mod+slash workspace 9
# bindsym $mod+asterisk workspace 10

# # move focused container to workspace
# bindsym $mod+Shift+quotedbl move container to workspace 1
# bindsym $mod+Shift+guillemotleft move container to workspace 2
# bindsym $mod+Shift+guillemotright move container to workspace 3
# bindsym $mod+Shift+4 move container to workspace 4
# bindsym $mod+Shift+5 move container to workspace 5
# bindsym $mod+Shift+at move container to workspace 6
# bindsym $mod+Shift+plus move container to workspace 7
# bindsym $mod+Shift+minus move container to workspace 8

# WARNING
# WARNING: This configuration file is a template for the i3-config-wizard to
# WARNING: generate a config which uses keysyms in your current layout. It does
# WARNING: not get loaded by i3. Please do not change it.
# WARNING

# i3 config file (v4)
#
# Please see http://i3wm.org/docs/userguide.html for a complete reference!

set $mod Mod4

# Font for window titles. Will also be used by the bar unless a different font
# is used in the bar {} block below.
#font pango:monospace 8

# This font is widely installed, provides lots of unicode glyphs, right-to-left
# text rendering and scalability on retina/hidpi displays (thanks to pango).
font pango:DejaVu Sans Mono 8

# Before i3 v4.8, we used to recommend this one as the default:
# font -misc-fixed-medium-r-normal--13-120-75-75-C-70-iso10646-1
# The font above is very space-efficient, that is, it looks good, sharp and
# clear in small sizes. However, its unicode glyph coverage is limited, the old
# X core fonts rendering does not support right-to-left and this being a bitmap
# font, it doesn’t scale on retina/hidpi displays.

# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

# start a terminal
bindcode $mod+36 exec i3-sensible-terminal

# kill focused window
bindcode $mod+Shift+24 kill

# start dmenu (a program launcher)
bindcode $mod+40 exec dmenu_run
# There also is the (new) i3-dmenu-desktop which only displays applications
# shipping a .desktop file. It is a wrapper around dmenu, so you need that
# installed.
# bindsym $mod+d exec --no-startup-id i3-dmenu-desktop

# change focus
bindcode $mod+43 focus left
bindcode $mod+44 focus down
bindcode $mod+45 focus up
bindcode $mod+46 focus right

# alternatively, you can use the cursor keys:
bindcode $mod+113 focus left
bindcode $mod+116 focus down
bindcode $mod+111 focus up
bindcode $mod+114 focus right

# move focused window
bindcode $mod+Shift+43 move left
bindcode $mod+Shift+44 move down
bindcode $mod+Shift+45 move up
bindcode $mod+Shift+46 move right

# alternatively, you can use the cursor keys:
bindcode $mod+Shift+113 move left
bindcode $mod+Shift+116 move down
bindcode $mod+Shift+111 move up
bindcode $mod+Shift+114 move right

# split in horizontal orientation
bindcode $mod+60 split h

# split in vertical orientation
bindcode $mod+55 split v

# enter fullscreen mode for the focused container
bindcode $mod+41 fullscreen toggle

# change container layout (stacked, tabbed, toggle split)
bindcode $mod+39 layout stacking
bindcode $mod+25 layout tabbed
bindcode $mod+26 layout toggle split

bindcode $mod+Shift+65 floating toggle

# change focus between tiling / floating windows
bindcode $mod+65 focus mode_toggle

# focus the parent container
bindcode $mod+38 focus parent

# focus the child container
#bindsym $mod+d focus child

# switch to workspace
bindcode $mod+10 workspace 1
bindcode $mod+11 workspace 2
bindcode $mod+12 workspace 3
bindcode $mod+13 workspace 4
bindcode $mod+14 workspace 5
bindcode $mod+15 workspace 6
bindcode $mod+16 workspace 7
bindcode $mod+17 workspace 8
bindcode $mod+18 workspace 9
bindcode $mod+19 workspace 10

bindcode $mod+67 workspace 11
bindcode $mod+68 workspace 12
bindcode $mod+69 workspace 13
bindcode $mod+70 workspace 14
bindcode $mod+71 workspace 15
bindcode $mod+72 workspace 16
bindcode $mod+73 workspace 17
bindcode $mod+74 workspace 18
bindcode $mod+75 workspace 19

# move focused container to workspace
bindcode $mod+Shift+10 move container to workspace 1
bindcode $mod+Shift+11 move container to workspace 2
bindcode $mod+Shift+12 move container to workspace 3
bindcode $mod+Shift+13 move container to workspace 4
bindcode $mod+Shift+14 move container to workspace 5
bindcode $mod+Shift+15 move container to workspace 6
bindcode $mod+Shift+16 move container to workspace 7
bindcode $mod+Shift+17 move container to workspace 8
bindcode $mod+Shift+18 move container to workspace 9
bindcode $mod+Shift+19 move container to workspace 10

bindcode $mod+Shift+67 move container to workspace 11
bindcode $mod+Shift+68 move container to workspace 12
bindcode $mod+Shift+69 move container to workspace 13
bindcode $mod+Shift+70 move container to workspace 14
bindcode $mod+Shift+71 move container to workspace 15
bindcode $mod+Shift+72 move container to workspace 16
bindcode $mod+Shift+73 move container to workspace 17
bindcode $mod+Shift+74 move container to workspace 18
bindcode $mod+Shift+75 move container to workspace 19

# reload the configuration file
bindcode $mod+Shift+54 reload
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindcode $mod+Shift+27 restart
# exit i3 (logs you out of your X session)
bindcode $mod+Shift+26 exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -b 'Yes, exit i3' 'i3-msg exit'"

# resize window (you can also use the mouse for that)
mode "resize" {
        # These bindings trigger as soon as you enter the resize mode

        # Pressing left will shrink the window’s width.
        # Pressing right will grow the window’s width.
        # Pressing up will shrink the window’s height.
        # Pressing down will grow the window’s height.
        bindcode 44 resize shrink width 10 px or 10 ppt
        bindcode 45 resize grow height 10 px or 10 ppt
        bindcode 46 resize shrink height 10 px or 10 ppt
        bindcode 47 resize grow width 10 px or 10 ppt

        # same bindings, but for the arrow keys
        bindcode 113 resize shrink width 10 px or 10 ppt
        bindcode 116 resize grow height 10 px or 10 ppt
        bindcode 111 resize shrink height 10 px or 10 ppt
        bindcode 114 resize grow width 10 px or 10 ppt

        # back to normal: Enter or Escape
        bindcode 36 mode "default"
        bindcode 9 mode "default"
}

bindcode $mod+27 mode "resize"



# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
bar {
        status_command i3blocks
        #tray_output primary
	position top
}

#Screenshot
bindsym --release Print exec --no-startup-id scrot '%Y-%m-%d.png' -e 'mv $f ~/screenshot/'
bindsym --release Shift+Print exec --no-startup-id scrot -u '%Y-%m-%d_.png' -e 'mv $f ~/screenshot/'

#Volume control
bindsym XF86AudioRaiseVolume exec --no-startup-id amixer -q -D pulse sset Master 5%+ && pkill -RTMIN+1 i3blocks 
bindsym XF86AudioLowerVolume exec --no-startup-id amixer -q -D pulse sset Master 5%- && pkill -RTMIN+1 i3blocks 
bindsym XF86AudioMute exec --no-startup-id amixer -q -D pulse sset Master toggle && pkill -RTMIN+1 i3blocks 

#Screen brightness
bindsym XF86MonBrightnessUp exec xbacklight -inc 10
bindsym XF86MonBrightnessDown exec xbacklight -dec 10

#Suspend
#bindsy XF86Sleep exec systemctl suspend

#Music Control
bindsym XF86AudioPlay exec playerctl --player vlc play-pause
bindsym XF86AudioPrev exec playerctl --player vlc previous
bindsym XF86AudioNext exec playerctl --player vlc next

#Calculator
bindsym XF86Calculator exec xcalc

#ScreenLock
bindsym $mod+Ctrl+l exec --no-startup-id i3lock -n -c 000000

#ScratchPad
bindcode $mod+48 move scratchpad
bindcode $mod+Ctrl+44 scratchpad show

#Disable focus on Dymola message
#no-focus [class="Dymola"]

#set rule for dual screen
workspace 1 output VGA1
workspace 2 output VGA1
workspace 3 output VGA1
workspace 4 output VGA1
workspace 5 output VGA1
workspace 6 output VGA1
workspace 7 output VGA1
workspace 8 output VGA1
workspace 9 output VGA1


workspace 11 output LVDS1
workspace 12 output LVDS1
workspace 13 output LVDS1
workspace 14 output LVDS1
workspace 15 output LVDS1
workspace 16 output LVDS1
workspace 17 output LVDS1
workspace 18 output LVDS1
workspace 19 output LVDS1
